import { config, fields, collection } from "@keystatic/core";
import { SLUG_RE } from "./src/lib/slug";

// storage: local until Phase 3 flips to GitHub-app-backed storage for
// non-technical collaborators. `quran` intentionally excluded — fixed
// 114-entry set generated by scripts/epub-import.ts, not day-to-day editable.
//
// fields.relationship only targets one collection, so it's used for person /
// topics[] / narrates_from[] refs. Polymorphic pairs (source_type/source_id,
// target_type/target_id, sharh_of/mukhtasar_of/hashiyah_on which can point at
// book OR poem) stay plain fields.select + fields.text — validate.ts (already
// CI-gated) does the actual cross-entity integrity check.

const slugField = (extraPatternNote = "") =>
  fields.slug({
    name: {
      label: `Slug (id) — لا تغيّره بعد النشر${extraPatternNote}`,
      validation: { pattern: { regex: SLUG_RE, message: "lowercase a-z0-9, single/double hyphens only" } },
    },
    slug: { generate: (name) => name },
  });

const statusField = fields.select({
  label: "الحالة",
  options: [
    { label: "مسودة", value: "draft" },
    { label: "مراجعة", value: "review" },
    { label: "منشور", value: "published" },
    { label: "مؤرشف", value: "archived" },
  ],
  defaultValue: "draft",
});

const sharedFields = {
  title: fields.text({ label: "العنوان" }),
  status: statusField,
  published_at: fields.date({ label: "تاريخ النشر" }),
  updated_at: fields.date({ label: "تاريخ التحديث", validation: { isRequired: false } }),
  aliases: fields.array(fields.text({ label: "Alias slug" }), {
    label: "أسماء بديلة (redirects)",
    itemLabel: (p) => p.value,
  }),
};

const topicsRelationship = fields.array(fields.relationship({ label: "الموضوع", collection: "topic" }), {
  label: "المواضيع",
  itemLabel: (p) => p.value ?? "—",
});

const attachmentsField = fields.array(
  fields.object({
    label: fields.text({ label: "التسمية" }),
    url: fields.url({ label: "الرابط" }),
    format: fields.select({
      label: "الصيغة",
      options: [
        { label: "pdf", value: "pdf" },
        { label: "epub", value: "epub" },
        { label: "docx", value: "docx" },
        { label: "zip", value: "zip" },
      ],
      defaultValue: "pdf",
    }),
    size_bytes: fields.integer({ label: "الحجم (بايت)", validation: { isRequired: false } }),
  }),
  { label: "المرفقات", itemLabel: (p) => p.fields.label.value },
);

export default config({
  storage: { kind: "github", repo: { owner: "Ahmed-Sinkeat", name: "athar-archive" } },
  collections: {
    announcement: collection({
      label: "الإعلانات (Announcements)",
      slugField: "slug",
      path: "src/content/announcement/*",
      format: { contentField: "body" },
      schema: {
        slug: slugField(),
        ...sharedFields,
        priority: fields.integer({ label: "الأولوية", defaultValue: 5, validation: { min: 1, max: 10 } }),
        expires_at: fields.date({ label: "تاريخ الانتهاء", validation: { isRequired: false } }),
        body: fields.markdoc({ label: "النص", extension: "md" }),
      },
    }),
    highlight: collection({
      label: "مختارات الأسبوع (Highlight)",
      slugField: "slug",
      path: "src/content/highlight/*",
      format: { contentField: "body" },
      schema: {
        slug: slugField(),
        ...sharedFields,
        kind: fields.select({
          label: "النوع",
          options: [
            { label: "آية", value: "آية" },
            { label: "حديث", value: "حديث" },
            { label: "بيت", value: "بيت" },
          ],
          defaultValue: "آية",
        }),
        reference: fields.text({ label: "المصدر/التخريج", validation: { isRequired: false } }),
        // Optional pair — plain text, not fields.select (no "unset" state). Valid: poem, book, article.
        source_type: fields.text({ label: "نوع المصدر", validation: { isRequired: false } }),
        source_id: fields.text({ label: "معرف المصدر (slug)", validation: { isRequired: false } }),
        body: fields.markdoc({ label: "النص", extension: "md" }),
      },
    }),
    subject: collection({
      label: "التصنيفات (Subjects)",
      slugField: "slug",
      path: "src/content/subject/*",
      format: { contentField: "body" },
      schema: {
        slug: slugField(),
        ...sharedFields,
        description: fields.text({ label: "الوصف", multiline: true, validation: { isRequired: false } }),
        body: fields.markdoc({ label: "النص", extension: "md" }),
      },
    }),
    topic: collection({
      label: "المواضيع (Topics)",
      slugField: "slug",
      path: "src/content/topic/*",
      format: { contentField: "body" },
      schema: {
        slug: slugField(),
        ...sharedFields,
        subject: fields.relationship({ label: "التصنيف الأب", collection: "subject" }),
        description: fields.text({ label: "الوصف", multiline: true, validation: { isRequired: false } }),
        body: fields.markdoc({ label: "النص", extension: "md" }),
      },
    }),
    term: collection({
      label: "المصطلحات (Terms)",
      slugField: "slug",
      path: "src/content/term/*",
      format: { contentField: "body" },
      schema: {
        slug: slugField(),
        ...sharedFields,
        definition: fields.text({ label: "التعريف الموجز", validation: { isRequired: false } }),
        topics: topicsRelationship,
        also_known_as: fields.array(fields.text({ label: "اسم بديل" }), {
          label: "أسماء أخرى",
          itemLabel: (p) => p.value,
        }),
        body: fields.markdoc({ label: "النص", extension: "md" }),
      },
    }),
    person: collection({
      label: "الأشخاص (People)",
      slugField: "slug",
      path: "src/content/person/*",
      format: { contentField: "body" },
      schema: {
        slug: slugField(),
        ...sharedFields,
        bio: fields.text({ label: "السيرة", multiline: true, validation: { isRequired: false } }),
        image: fields.text({ label: "صورة (R2 path)", validation: { isRequired: false } }),
        born: fields.text({ label: "الميلاد", validation: { isRequired: false } }),
        died: fields.text({ label: "الوفاة", validation: { isRequired: false } }),
        location: fields.text({ label: "الموطن", validation: { isRequired: false } }),
        // fields.select forces a value (no "unset" state) — kept as free text since
        // this is optional in the Zod schema. Valid values: الجاهلي، صدر الإسلام،
        // الأموي، العباسي، الأندلسي، المتأخّر، الحديث. Keep in sync with ERA_VALUES (src/lib/display.ts).
        era: fields.text({ label: "العصر الأدبي (للشعراء)", validation: { isRequired: false } }),
        // Valid values: الصحابة، التابعون، أتباع التابعين، المتقدمون، المتوسطون،
        // المتأخرون، المعاصرون. Keep in sync with TABAQA_VALUES (src/lib/display.ts).
        tabaqa: fields.text({ label: "الطبقة العلمية (للعلماء)", validation: { isRequired: false } }),
        also_known_as: fields.array(fields.text({ label: "اسم بديل" }), {
          label: "أسماء وكُنى أخرى",
          itemLabel: (p) => p.value,
        }),
        aqeedah: fields.text({ label: "العقيدة", validation: { isRequired: false } }),
        rutba: fields.text({ label: "رتبة الجرح والتعديل", validation: { isRequired: false } }),
        narrates_from: fields.array(fields.relationship({ label: "يروي عن", collection: "person" }), {
          label: "شيوخه",
          itemLabel: (p) => p.value ?? "—",
        }),
        body: fields.markdoc({ label: "النص", extension: "md" }),
      },
    }),
    article: collection({
      label: "المقالات (Articles)",
      slugField: "slug",
      path: "src/content/article/*",
      format: { contentField: "body" },
      schema: {
        slug: slugField(),
        ...sharedFields,
        person: fields.relationship({ label: "الكاتب", collection: "person" }),
        topics: topicsRelationship,
        audio: fields.text({ label: "معرف الصوتية (slug)", validation: { isRequired: false } }),
        description: fields.text({ label: "الوصف", validation: { isRequired: false } }),
        attachments: attachmentsField,
        body: fields.markdoc({ label: "النص", extension: "md" }),
      },
    }),
    question: collection({
      label: "المسائل (Questions)",
      slugField: "slug",
      path: "src/content/question/*",
      format: { contentField: "body" },
      schema: {
        slug: slugField(),
        ...sharedFields,
        person: fields.relationship({ label: "الشخص", collection: "person" }),
        topics: fields.array(fields.relationship({ label: "الموضوع", collection: "topic" }), {
          label: "المواضيع (مطلوب)",
          itemLabel: (p) => p.value ?? "—",
          validation: { length: { min: 1 } },
        }),
        body: fields.markdoc({ label: "النص", extension: "md" }),
      },
    }),
    benefit: collection({
      label: "الفوائد (Benefits)",
      slugField: "slug",
      path: "src/content/benefit/*",
      format: { contentField: "body" },
      schema: {
        slug: slugField(),
        ...sharedFields,
        person: fields.relationship({ label: "الشخص", collection: "person" }),
        topics: topicsRelationship,
        // Optional pair — plain text, not fields.select (no "unset" state). Valid: book, article, poem.
        source_type: fields.text({ label: "نوع المصدر", validation: { isRequired: false } }),
        source_id: fields.text({ label: "معرف المصدر (slug)", validation: { isRequired: false } }),
        body: fields.markdoc({ label: "النص", extension: "md" }),
      },
    }),
    audio: collection({
      label: "الصوتيات (Audio)",
      slugField: "slug",
      path: "src/content/audio/*",
      format: { contentField: "body" },
      schema: {
        slug: slugField(),
        ...sharedFields,
        source_type: fields.select({
          label: "نوع المصدر",
          options: [
            { label: "book", value: "book" },
            { label: "poem", value: "poem" },
            { label: "article", value: "article" },
          ],
          defaultValue: "book",
        }),
        source_id: fields.text({ label: "معرف المصدر (slug)" }),
        url: fields.url({ label: "الرابط" }),
        format: fields.select({
          label: "الصيغة",
          options: [
            { label: "opus", value: "opus" },
            { label: "mp3", value: "mp3" },
          ],
          defaultValue: "opus",
        }),
        duration: fields.text({ label: "المدة", validation: { isRequired: false } }),
        size_bytes: fields.integer({ label: "الحجم (بايت)", validation: { isRequired: false } }),
      },
    }),
    // book / poem / annotation — Phase 0 spike confirmed fields.markdoc round-trips
    // the 4150-line book fixture and the poem's inline "---" hemistich separator
    // byte-identical, so bodies go through the normal editor (no metadata-only fallback).
    book: collection({
      label: "الكتب (Books)",
      slugField: "slug",
      path: "src/content/book/*",
      format: { contentField: "body" },
      schema: {
        slug: slugField(),
        ...sharedFields,
        person: fields.relationship({ label: "المؤلف", collection: "person" }),
        // Optional enums kept as free text — fields.select has no "unset" state.
        // Valid values: kind (متن، مرجع، مجموع); genre (قرآن، حديث، تراجم);
        // work_type (see workTypeField, src/content.config.ts); transcript_status
        // (مراجَع، قيد المراجعة); hadith_category (امهات الكتب، كتب الآثار،
        // أجزاء حديثية، تخريج، علل، عام).
        kind: fields.text({ label: "التصنيف الدراسي", validation: { isRequired: false } }),
        genre: fields.text({ label: "القسم", validation: { isRequired: false } }),
        sharh_of: fields.text({ label: "شرح لكتاب (slug)", validation: { isRequired: false } }),
        mukhtasar_of: fields.text({ label: "مختصر لكتاب (slug)", validation: { isRequired: false } }),
        hashiyah_on: fields.text({ label: "حاشية على كتاب (slug)", validation: { isRequired: false } }),
        work_type: fields.text({ label: "نوع العمل", validation: { isRequired: false } }),
        transcript_status: fields.text({ label: "حالة التفريغ", validation: { isRequired: false } }),
        hadith_category: fields.text({ label: "تصنيف كتب الحديث", validation: { isRequired: false } }),
        topics: topicsRelationship,
        authored_year: fields.integer({ label: "سنة التصنيف (هجري)", validation: { isRequired: false } }),
        description: fields.text({ label: "الوصف", validation: { isRequired: false } }),
        edition: fields.text({ label: "الطبعة", validation: { isRequired: false } }),
        cover: fields.text({ label: "صورة الغلاف (R2 path)", validation: { isRequired: false } }),
        attachments: attachmentsField,
        body: fields.markdoc({ label: "النص", extension: "md" }),
      },
    }),
    poem: collection({
      label: "المنظومات (Poems)",
      slugField: "slug",
      path: "src/content/poem/*",
      format: { contentField: "body" },
      schema: {
        slug: slugField(),
        ...sharedFields,
        person: fields.relationship({ label: "الناظم", collection: "person" }),
        topics: topicsRelationship,
        work_type: fields.text({ label: "نوع العمل", validation: { isRequired: false } }),
        authored_year: fields.integer({ label: "سنة النظم (هجري)", validation: { isRequired: false } }),
        description: fields.text({ label: "الوصف", validation: { isRequired: false } }),
        attachments: attachmentsField,
        body: fields.markdoc({ label: "النص", extension: "md" }),
      },
    }),
    annotation: collection({
      label: "الشروح والحواشي (Annotations)",
      slugField: "slug",
      path: "src/content/annotation/*",
      format: { contentField: "body" },
      schema: {
        slug: slugField(),
        ...sharedFields,
        target_type: fields.select({
          label: "نوع الهدف",
          options: [
            { label: "book", value: "book" },
            { label: "poem", value: "poem" },
            { label: "quran", value: "quran" },
          ],
          defaultValue: "book",
        }),
        target_id: fields.text({ label: "معرف الهدف (slug)" }),
        anchor: fields.text({ label: "الموضع (anchor)" }),
        kind: fields.select({
          label: "النوع",
          options: [
            { label: "شرح", value: "شرح" },
            { label: "حاشية", value: "حاشية" },
            { label: "تخريج", value: "تخريج" },
            { label: "إعراب", value: "إعراب" },
            { label: "تفسير", value: "تفسير" },
          ],
          defaultValue: "شرح",
        }),
        // Valid values: صحيح، حسن، ضعيف، موضوع.
        grade: fields.text({ label: "الدرجة", validation: { isRequired: false } }),
        annotator: fields.relationship({ label: "الشارح", collection: "person" }),
        phrase: fields.text({ label: "العبارة المحددة", validation: { isRequired: false } }),
        // Optional pair — plain text, not fields.select (no "unset" state). Valid: book, poem, article.
        source_type: fields.text({ label: "نوع المصدر", validation: { isRequired: false } }),
        source_id: fields.text({ label: "معرف المصدر (slug)", validation: { isRequired: false } }),
        body: fields.markdoc({ label: "النص", extension: "md" }),
      },
    }),
  },
});
