package com.atharchive.core.data.content

import java.util.Base64
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Test

class SignedRootVerifierTest {
    private val publicKey by lazy {
        SignedRootVerifier.rsaPublicKeyFromX509(Base64.getDecoder().decode(PUBLIC_KEY_DER))
    }

    @Test
    fun acceptsNodeGeneratedRsa3072Envelope() {
        val payload = SignedRootVerifier.verify(
            CROSS_LANGUAGE_ENVELOPE.toByteArray(),
            mapOf("android-cross-language-test" to publicKey),
        )

        assertEquals("a466ede4f85dc5ed", payload.generationId)
        assertEquals("74865a0f2b41c5130035244bb28eed490b35c927012180356bfba85772c73efc", payload.catalog.hash)
        assertEquals(4_673, payload.catalog.size)
    }

    @Test
    fun acceptsAnOverlapEnvelopeWhenOneSignatureIsTrusted() {
        val original = AppContentJson.decodeFromString<SignedEnvelope>(CROSS_LANGUAGE_ENVELOPE)
        val overlap = original.copy(
            signatures = listOf(RootSignature("future-key", "SHA256withRSA", "not_base64!")) + original.signatures,
        )

        val payload = SignedRootVerifier.verify(
            AppContentJson.encodeToString(overlap).toByteArray(),
            mapOf("android-cross-language-test" to publicKey),
        )

        assertEquals(APP_CONTENT_SCHEMA, payload.schema)
    }

    @Test
    fun rejectsTamperingUnknownKeysAndUnsupportedAlgorithms() {
        val original = AppContentJson.decodeFromString<SignedEnvelope>(CROSS_LANGUAGE_ENVELOPE)
        val changedPayload = original.payload!!.dropLast(1) + if (original.payload.last() == 'A') "B" else "A"

        assertThrows(ContentIntegrityException::class.java) {
            SignedRootVerifier.verify(
                AppContentJson.encodeToString(original.copy(payload = changedPayload)).toByteArray(),
                mapOf("android-cross-language-test" to publicKey),
            )
        }
        assertThrows(ContentIntegrityException::class.java) {
            SignedRootVerifier.verify(CROSS_LANGUAGE_ENVELOPE.toByteArray(), emptyMap())
        }
        assertThrows(ContentIntegrityException::class.java) {
            val unsupported = original.copy(
                signatures = original.signatures.map { it.copy(alg = "SHA512withRSA") },
            )
            SignedRootVerifier.verify(
                AppContentJson.encodeToString(unsupported).toByteArray(),
                mapOf("android-cross-language-test" to publicKey),
            )
        }
    }

    @Test
    fun rejectsOversizedInputBeforeParsing() {
        assertThrows(ContentIntegrityException::class.java) {
            SignedRootVerifier.verify(ByteArray(MAX_SIGNED_DOCUMENT_BYTES + 1), emptyMap())
        }
    }

    private companion object {
        // Generated by Node's crypto module from the exact app/v2 payload bytes emitted by
        // scripts/gen-app-content.ts. The private test key was discarded; only this public
        // compatibility vector belongs in the repository.
        const val PUBLIC_KEY_DER =
            "MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAvk2JAiMe+ylJPhecJGt+m2WuzTAITDPEp3TfLL64rfxG8EJHoslegxWPgzcQSolQ/qmC7gbX+OEQuuHKcRy3oSbmLruoSQQAb2QbKXSL+Nbp6xBbC9w5oUvik1MmsnplNBPI8oZT0dDFZTmVNAdlmPTCEOWbs0FFGww0/JKXufp5MiEaYTPFfI0UF463O0UfeCzsQUCdISPhASuSeENHnru7N33AeqPrkCaqGHJ85CbEX7+jTzxgyj67oaEubVrmWPymSrwoH4LGkFxm2q7EhQ1MFHC7VIPybsmIlBXckobNEZGSGi5o1ZrSG27H582Ecfxv66uLSeVLIX3QSnW2V4aGspg/X44YImY70WELW33n98bqHonuGfBLYVSHwWJP0o6/z7ubb4+hTCeN40q858x8WbGQ45b7N3xpiwz6urlIF5wMnSxiAqCsU+Nzoz8Js60WvKFbqRPD5D/HAgF0CyzVdWS92fBr2SLvn3euxbUJkZ65xw5UxFYI74icVJ0ZAgMBAAE="

        const val CROSS_LANGUAGE_ENVELOPE =
            """{"envelope":1,"payload":"eyJzY2hlbWEiOjIsImdlbmVyYXRpb25JZCI6ImE0NjZlZGU0Zjg1ZGM1ZWQiLCJjYXRhbG9nIjp7InBhdGgiOiJjYXRhbG9nLzc0ODY1YTBmMmI0MWM1MTMwMDM1MjQ0YmIyOGVlZDQ5MGIzNWM5MjcwMTIxODAzNTZiZmJhODU3NzJjNzNlZmMuanNvbiIsImhhc2giOiI3NDg2NWEwZjJiNDFjNTEzMDAzNTI0NGJiMjhlZWQ0OTBiMzVjOTI3MDEyMTgwMzU2YmZiYTg1NzcyYzczZWZjIiwic2l6ZSI6NDY3M30sInRvbWJzdG9uZXMiOnsicGF0aCI6InRvbWJzdG9uZXMvNzM3ZjdiMmFkYTBlMjhlZGMxNDBlOTFhZDZiNmMyMDA0YmQ3N2VjZTRmZWM5ZDgyYjhiZWY4YTQ1NjMzMjVlNC5qc29uIiwiaGFzaCI6IjczN2Y3YjJhZGEwZTI4ZWRjMTQwZTkxYWQ2YjZjMjAwNGJkNzdlY2U0ZmVjOWQ4MmI4YmVmOGE0NTYzMzI1ZTQiLCJzaXplIjo0N30sIm1pbkFwcFNjaGVtYSI6Mn0K","signatures":[{"keyId":"android-cross-language-test","alg":"SHA256withRSA","value":"grBlQkFu4EfBpASvjfdfzNf2n1BJaq-Ljq79LJxjEgE62Svbc2UYmZQ67LRi8WEGZK2lQ9jRb-qEBEpOu3ZIjCb7NbWbpCUKF6v38hlpqbJqiBlmjZZ9JiF8YTtUOL43KCamD12QwrNkIUb2xA7yxfwGN6k0c_ukndbfUwsKoo2Nd5hICExdeKfHDcOdOR71xNxLJPkqDSsqi_77YEooI1z_9fcSWYGAX6IEMJftndKV9aJNyBcV3FE40RNpPL0ylvYCV22O3juDoPeJHq4uEB8hyP4Az1hwRZCuVrwUJgbBGa7sETgGjpt_jWLfpAbmKtZDVlXt-uE3FwVSS-o27O4eh9p568ptbx1Z9uOp0X2OMFzXuNUULLhyKOXAUQuq7DciiLSrQWpD8PiCKeBCry-djHeCn185HJUewPMOhGPW8wcDG4v6L2UGN2L9-8MuNghd3_irVO4xKQPOkwe-pnm8pVHkNudrPGwgt0nquUvU7qVX_UWGxr-PvbCMBwAF"}]}"""
    }
}
